DELIMITER $$
CREATE PROCEDURE ADD_CUSTOMER(
	IN FIRST_NAME VARCHAR(30)
,	IN LAST_NAME VARCHAR(30)
,	IN PHONE_NUMBER VARCHAR(15)
,	IN STREET_NUMBER VARCHAR(4)
,	IN STREET_NAME VARCHAR(30)
,	IN CITY VARCHAR(30)
,	IN PROVINCE VARCHAR(2)
,	IN POSTAL_CODE VARCHAR(7)
,	IN COUNTRY VARCHAR(50)
,	OUT CUSTOMER_ID INT)
BEGIN
    START TRANSACTION; -- Begin a transaction
    INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, PHONE_NUMBER, STREET_NUMBER, STREET_NAME, CITY, PROVINCE, POSTAL_CODE, COUNTRY, DISCOUNT_CODE) 
    VALUES (FIRST_NAME, LAST_NAME, PHONE_NUMBER, STREET_NUMBER, STREET_NAME, CITY, PROVINCE, POSTAL_CODE, COUNTRY, 0);
    IF ROW_COUNT() > 0 THEN -- ROW_COUNT() returns the number of rows inserted
        COMMIT; -- Finalize the transaction
	SELECT LAST_INSERT_ID() INTO CUSTOMER_ID;
    ELSE
        ROLLBACK; -- Revert all changes made before the transaction began
    END IF;
END$$
DELIMITER ;