DELIMITER $$
CREATE PROCEDURE CANCEL_TRANSACTION(
	IN TRANSACTIONID INT)
BEGIN
	DECLARE TRANSACTIONDATE DATE;
	
    SELECT TRANSACTION_DATE INTO TRANSACTIONDATE FROM TRANSACTIONS WHERE TRANSACTION_ID = TRANSACTION_ID;
	IF TRANSACTIONDATE BETWEEN DATE_SUB(NOW(), INTERVAL 30 DAY) AND NOW() THEN
		DELETE FROM TRANSACTIONS_ITEM WHERE TRANSACTION_ID = TRANSACTIONID;
		DELETE FROM TRANSACTIONS WHERE TRANSACTIONS_ID = TRANSACTIONID;
    END IF;
END$$
DELIMITER ;

