DELIMITER $$
CREATE PROCEDURE CANCEL_TRANSACTION(
	IN TRANSACTIONID INT)
BEGIN
    
	DELETE FROM TRANSACTIONS_ITEM WHERE TRANSACTION_ID = TRANSACTIONID;
	DELETE FROM TRANSACTIONS WHERE TRANSACTIONS_ID = TRANSACTIONID;
    
END$$
DELIMITER ;