DELIMITER $$
CREATE PROCEDURE UPDATE_TOTAL_PURCHASE_PRICE(
	IN TRANSACTIONID INT)
BEGIN
	DECLARE DC INT DEFAULT 0;
    DECLARE TOTALCOST FLOAT DEFAULT 0;
    DECLARE TOTALPURCHASSEPRICE FLOAT DEFAULT 0;
	DECLARE CUSTOMERID INT DEFAULT 0;

    START TRANSACTION; -- Begin a transaction
	SELECT CUSTOMER_ID INTO CUSTOMERID FROM TRANSACTIONS WHERE TRANSACTIONS_ID = TRANSACTIONID;
    SELECT TOTAL_PRICE INTO TOTALPURCHASSEPRICE FROM TRANSACTIONS WHERE TRANSACTIONS_ID = TRANSACTIONID;
    SET TOTALCOST = TOTALPURCHASSEPRICE;
    SELECT DISCOUNT_CODE INTO DC FROM CUSTOMER WHERE CUSTOMER_ID = CUSTOMERID;
    
    SET TOTALPURCHASSEPRICE = TOTALCOST*(1-2.5*DC/100);
    UPDATE TRANSACTIONS SET TOTAL_PRICE = TOTALPURCHASSEPRICE WHERE TRANSACTIONS_ID = TRANSACTIONID;

    IF ROW_COUNT() > 0 THEN -- ROW_COUNT() returns the number of rows inserted
        COMMIT; -- Finalize the transaction
    ELSE
        ROLLBACK; -- Revert all changes made before the transaction began
    END IF;
END$$
DELIMITER ;