DELIMITER $$
CREATE PROCEDURE UPDATE_DISCOUNT_CODE(
	IN CUSTOMERID INT)
BEGIN
	DECLARE DISCOUNTCODE INT DEFAULT 0;
    DECLARE MAXTRANSACTIONDATE DATE;
    DECLARE TOTALPURCHASSEPRICE FLOAT DEFAULT 0;
    
    SET MAXTRANSACTIONDATE = CURDATE() - INTERVAL 5 YEAR;

    START TRANSACTION; -- Begin a transaction
    
    SELECT SUM(TOTAL_PRICE) INTO TOTALPURCHASSEPRICE FROM TRANSACTIONS WHERE CUSTOMER_ID = CUSTOMERID AND TRANSACTION_DATE >= MAXTRANSACTIONDATE GROUP BY CUSTOMER_ID;
    
    IF TOTALPURCHASSEPRICE > 500 THEN
    SET DISCOUNTCODE = 5;
    ELSEIF TOTALPURCHASSEPRICE > 400 AND TOTALPURCHASSEPRICE <= 500 THEN
    SET DISCOUNTCODE = 4;
    ELSEIF TOTALPURCHASSEPRICE > 300 AND TOTALPURCHASSEPRICE <= 400 THEN
    SET DISCOUNTCODE = 3;
    ELSEIF TOTALPURCHASSEPRICE > 200 AND TOTALPURCHASSEPRICE <= 300 THEN
    SET DISCOUNTCODE = 2;
    ELSEIF TOTALPURCHASSEPRICE > 100 AND TOTALPURCHASSEPRICE <= 200 THEN
    SET DISCOUNTCODE = 1;
    END IF;
    
    IF DISCOUNTCODE > 0 THEN
    UPDATE CUSTOMER SET DISCOUNT_CODE = DISCOUNTCODE WHERE CUSTOMER_ID = CUSTOMERID;
    END IF;
    IF ROW_COUNT() > 0 THEN -- ROW_COUNT() returns the number of rows inserted
        COMMIT; -- Finalize the transaction
    ELSE
        ROLLBACK; -- Revert all changes made before the transaction began
    END IF;
END$$
DELIMITER ;