INSERT INTO AUTHOR (lname, fname, email) SELECT DISTINCT lname, fname, email FROM STAGING_AUTHOR;

INSERT INTO ARTICLE (article_Id, TITLE, PAGES) SELECT article_id, title, pages from STAGING_ARTICLE WHERE LENGTH(title)<=200;

INSERT INTO ARTICLE_AUTHORS (ARTICLE_ID, AUTHOR_ID) SELECT STAGING_AUTHOR.article_id,AUTHOR._id FROM (SELECT DISTINCT article_id, lname, fname, email FROM STAGING_AUTHOR) STAGING_AUTHOR,AUTHOR 
WHERE STAGING_AUTHOR.lname = AUTHOR.lname
AND STAGING_AUTHOR.fname = AUTHOR.fname
AND STAGING_AUTHOR.email = AUTHOR.email
AND article_id IN (SELECT article_id from ARTICLE); 

INSERT INTO MAGAZINE (name) SELECT DISTINCT journal FROM STAGING_ARTICLE WHERE LENGTH(journal)<=50;

INSERT IGNORE INTO MAGAZINE_VOLUME (MAGAZINE_ID, VOLUME_NUMBER, MAGAZINE_YEAR) 
SELECT DISTINCT MAGAZINE._id, STAGING_ARTICLE.volume, STAGING_ARTICLE.year 
FROM STAGING_ARTICLE, MAGAZINE
WHERE STAGING_ARTICLE.journal = MAGAZINE.name;

INSERT INTO MAGAZINE_ARTICLE (ARTICLE_ID, MAGAZINE_ID, VOLUME_NUMBER) 
SELECT STAGING_ARTICLE.article_id, MAGAZINE._id, STAGING_ARTICLE.volume 
FROM (SELECT DISTINCT article_id, volume, journal FROM STAGING_ARTICLE) STAGING_ARTICLE,MAGAZINE 
WHERE STAGING_ARTICLE.journal = MAGAZINE.name
AND article_id IN (SELECT article_id from ARTICLE)
AND MAGAZINE._id in (SELECT MAGAZINE_ID FROM MAGAZINE_VOLUME);

