DROP TABLE if exists ARTICLE_ITEMS;
#
DROP TABLE if exists ARTICLE_AUTHORS;
#
DROP TABLE if exists MAGAZINE_ARTICLE;
#
DROP TABLE if exists MAGAZINE_VOLUME;
#
DROP TABLE if exists TRANSACTIONS_ITEM;
#
DROP TABLE if exists TRANSACTIONS;
#
DROP TABLE if exists EMPLOYEE_HOURS;
#

/*1. New library items*/

DROP TABLE if exists ARTICLE;
#
CREATE
  TABLE IF NOT EXISTS ARTICLE
  (
    article_id INT NOT NULL AUTO_INCREMENT,
    TITLE      VARCHAR(200),
    PAGES       VARCHAR(30),
    PRIMARY KEY(article_id)
  )
  ENGINE = INNODB;

CREATE
  TABLE IF NOT EXISTS ARTICLE_ITEMS
  (
    ARTICLE_ID INT NOT NULL,
    ITEM_ID  BIGINT NOT NULL,
    PRIMARY KEY(ARTICLE_ID, ITEM_ID)
  )
  ENGINE = INNODB;

ALTER TABLE ARTICLE_ITEMS ADD FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE(article_id);
ALTER TABLE ARTICLE_ITEMS ADD FOREIGN KEY (ITEM_ID) REFERENCES ITEM(_id);

CREATE
  TABLE IF NOT EXISTS ARTICLE_AUTHORS
  (
    ARTICLE_ID INT NOT NULL,
    AUTHOR_ID  INT NOT NULL,
    PRIMARY KEY(ARTICLE_ID, AUTHOR_ID)
  )
  ENGINE = INNODB;

ALTER TABLE ARTICLE_AUTHORS ADD FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE(article_id);
ALTER TABLE ARTICLE_AUTHORS ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(_id);

CREATE
  TABLE IF NOT EXISTS MAGAZINE_VOLUME
  (
    MAGAZINE_ID INT NOT NULL,
    VOLUME_NUMBER VARCHAR(10),
    MAGAZINE_YEAR VARCHAR(4),
    PRIMARY KEY (MAGAZINE_ID, VOLUME_NUMBER, MAGAZINE_YEAR)
  )
  ENGINE = INNODB;

ALTER TABLE MAGAZINE_VOLUME ADD FOREIGN KEY (MAGAZINE_ID) REFERENCES MAGAZINE(_id);
  
CREATE UNIQUE INDEX mv_id
ON MAGAZINE_VOLUME (VOLUME_NUMBER);
  
CREATE
  TABLE IF NOT EXISTS MAGAZINE_ARTICLE
  (
    ARTICLE_ID  INT NOT NULL,
    MAGAZINE_ID INT NOT NULL,
    VOLUME_NUMBER   VARCHAR(10),
    PRIMARY KEY(ARTICLE_ID,MAGAZINE_ID,VOLUME_NUMBER)
  )
  ENGINE = INNODB;
  
ALTER TABLE MAGAZINE_ARTICLE ADD FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE(article_id);
ALTER TABLE MAGAZINE_ARTICLE ADD FOREIGN KEY (MAGAZINE_ID) REFERENCES MAGAZINE_VOLUME(MAGAZINE_ID);
ALTER TABLE MAGAZINE_ARTICLE ADD FOREIGN KEY (VOLUME_NUMBER) REFERENCES MAGAZINE_VOLUME(VOLUME_NUMBER);


/*2. Customers and Transactions*/

DROP TABLE if exists CUSTOMER;
# 
CREATE
  TABLE IF NOT EXISTS CUSTOMER
  (
    customer_id   INT NOT NULL AUTO_INCREMENT,
    FIRST_NAME    VARCHAR(30) NOT NULL,
    LAST_NAME     VARCHAR(30) NOT NULL,
    PHONE_NUMBER  VARCHAR(15),
    STREET_NUMBER VARCHAR(4),
    STREET_NAME   VARCHAR(30),
    CITY          VARCHAR(30),
    PROVINCE      VARCHAR(2),
    POSTAL_CODE   VARCHAR(7),
    COUNTRY       VARCHAR(50),
    DISCOUNT_CODE VARCHAR(1),
    PRIMARY KEY(customer_id)
  )
  ENGINE = INNODB;

CREATE
  TABLE IF NOT EXISTS TRANSACTIONS
  (
    transactions_id BIGINT NOT NULL AUTO_INCREMENT,
    CUSTOMER_ID INT NOT NULL,
    TRANSACTION_DATE DATE NOT NULL,
    TOTAL_PRICE FLOAT(8,2) NOT NULL,
    PRIMARY KEY(transactions_id)
  )
  ENGINE = INNODB;

ALTER TABLE TRANSACTIONS ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(customer_id);
  
CREATE
  TABLE IF NOT EXISTS TRANSACTIONS_ITEM
  (
    TRANSACTION_ID BIGINT NOT NULL,
    ITEM_ID BIGINT NOT NULL,
    PRIMARY KEY(TRANSACTION_ID,ITEM_ID)
  )
  ENGINE = INNODB;

ALTER TABLE TRANSACTIONS_ITEM ADD FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS(transactions_id);
ALTER TABLE TRANSACTIONS_ITEM ADD FOREIGN KEY (ITEM_ID) REFERENCES ITEM(_id);


/*3. Monthly Expenses*/

DROP TABLE if exists MONTHLY_EXPENSE;
# 
CREATE
  TABLE IF NOT EXISTS MONTHLY_EXPENSE
  (
    _id INT NOT NULL AUTO_INCREMENT,
    MONTH DATE NOT NULL,
    ELECTRICITY FLOAT(8,2),
    HEAT FLOAT(8,2),
    WATER FLOAT(8,2),
    RENT FLOAT(8,2),
    WAGES FLOAT(8,2),
    PRIMARY KEY(_id)
  )
  ENGINE = INNODB;


DROP TABLE if exists EMPLOYEE;
# 
CREATE
  TABLE IF NOT EXISTS EMPLOYEE
  (
    employee_id INT NOT NULL AUTO_INCREMENT,
    SIN         VARCHAR(25) NOT NULL,
    PRIMARY KEY(employee_id)
  )
  ENGINE = INNODB;

CREATE
  TABLE IF NOT EXISTS EMPLOYEE_HOURS
  (
    EMPLOYEE_ID INT NOT NULL,
    DAY_OF_MONTH DATE NOT NULL,
    HOURS FLOAT(8,2) NOT NULL,
    PRIMARY KEY(EMPLOYEE_ID,DAY_OF_MONTH)
  )
  ENGINE = INNODB;

ALTER TABLE EMPLOYEE_HOURS ADD FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(employee_id);

DROP TABLE if exists STAGING_ARTICLE;
#
CREATE
  TABLE IF NOT EXISTS STAGING_ARTICLE
  (
    _id INT NOT NULL AUTO_INCREMENT,
	article_id INT NOT NULL,
    title      VARCHAR(290),
    pages       VARCHAR(30),
	year VARCHAR(4),
	volume VARCHAR(10),
	journal VARCHAR(200),
    PRIMARY KEY(_id)
  )
  ENGINE = INNODB;
  
 DROP TABLE if exists STAGING_AUTHOR;
#
CREATE
  TABLE IF NOT EXISTS STAGING_AUTHOR
  (
  _id INT NOT NULL AUTO_INCREMENT,
  article_id INT NOT NULL,
  lname varchar(30) NOT NULL,
  fname varchar(30),
  email varchar(50),
  PRIMARY KEY(_id)
  )
  ENGINE = INNODB;